### ISSUE TITLE
Use asyncio (or similar, like Twisted) for implementing the bot. 

### ISSUE THREAD

**Issue by psaavedra** [psaavedra/matrix-bot#22]
Use asyncio (or similar, like Twisted) for implementing the bot. This way long-running operations (like fetching feeds) will be done asynchronously and other code can run in the meanwhile.

**Comment by jmunhoz** [comment]
Commeting in this ticket to know if you could have share some update about this enhancement. It would be really useful having this support in place to handle async workloads in plugins. The placeholders are in place but it looks not implemented yet:

https://github.com/psaavedra/matrix-bot/blob/4f598d891a0c7b43ed5ef8683a8b33bdbb2e6d0e/matrixbot/matrix.py#L683
