### ISSUE TITLE
Communication with the bot in the same 1-to-1 room

### ISSUE THREAD

**Issue by jmunhoz** [psaavedra/matrix-bot#36]
Currently if you have two or more 1-to-1 rooms open with the bot, you may not receive the response to a command in the same room in which you sent it.

In some cases this is confusing in that the user may think that the bot did not process the message or that the task is taking much longer than necessary when the response may actually have been received and is available in another room.

**Comment by psaavedra** [comment]
Fixed in https://github.com/psaavedra/matrix-bot/pull/39 [R260](https://github.com/psaavedra/matrix-bot/pull/39/files#diff-091ee3cac1b8af19ddfe8aea80677a0b5af4a71aca93161ff53fdeb19c265c56R260)
