### ISSUE TITLE
Regression on 'invite' and 'kick' commands

### ISSUE THREAD

**Issue by jmunhoz** [psaavedra/matrix-bot#58]
The 'invite' command is failing with the current main branch. The bug lives at:

https://github.com/psaavedra/matrix-bot/blob/4ba0a3779adf9edb44b2e8d5a4f0e8f8a022b764/matrixbot/matrix.py#L981

The 'by' var looks one typo. I think it should be 'command' but adding 'command' instead of 'by' raises 'No users founds' error.

The following code works ok:

self.do_command("invite_user", sender, room_id, event["content"]["body"])

I think the bug is here:

https://github.com/psaavedra/matrix-bot/blob/4ba0a3779adf9edb44b2e8d5a4f0e8f8a022b764/matrixbot/matrix.py#L947-L958

**Comment by psaavedra** [comment]
Based on the differences in a7aa7176:

``` diff
-            if self.is_command(body, "invite"):
-                self.do_command("invite_user", sender, room_id, body)
-            elif self.is_command(body, "kick"):
-                self.do_command("kick_user", sender, room_id, body)
-            elif self.is_command(body, "join"):
+            if self.is_command(command, "invite"):
+                self.do_command("invite_user", sender, room_id, by)
+            elif self.is_command(command, "kick"):
+                self.do_command("kick_user", sender, room_id, command)
```

Looks like the typo is `s/by/command/`, right?

**Comment by jmunhoz** [comment]
Yes, the fix should be s/by/command/ but it does not work as expected. With the potential fix in place it shows the ''No users founds' message as commented above. The first line in _get_commands would do the thing but then the body is touched.

**Comment by psaavedra** [comment]
> The 'by' var looks one typo. I think it should be 'command' but adding 'command' instead of 'by' raises 'No users founds' error.

Are you sure about that?. Can you check if you are not trying to add a user already member of the room?. Please note L246: `selected_users = set(self._get_selected_users(body_arg_list)).difference(room_members)`. So if you are trying to add an user already added this will be ignored.

**Comment by jmunhoz** [comment]
Yes, confirmed. It is not working with 'command'. The same test with event["content"]["body"] works as expected.

**Comment by psaavedra** [comment]
That is odd can you confirm the if the `kick` command is working. Both share almost the same logic.

**Comment by psaavedra** [comment]
@jmunhoz can you try this https://github.com/psaavedra/matrix-bot/pull/59 ?

**Comment by jmunhoz** [comment]
Sure! 'invite' is working on my side but 'invite' command continues failing with 'No users found' error.
